# Generated by Django 3.2.6 on 2021-09-02 03:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_alter_car_vin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Ответ')),
            ],
            options={
                'verbose_name': 'Ответ пользователя',
                'verbose_name_plural': 'Ответы пользователя',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Вопрос')),
                ('question_type', models.CharField(choices=[('1', 'Ответ текстом'), ('2', 'Ответ с выбором одного варианта'), ('3', 'Ответ с выбором нескольких вариантов')], max_length=150, verbose_name='Тип вопроса')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Responder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=50, verbose_name='ip пользователя')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_created=True, verbose_name='Дата создания опроса')),
                ('title', models.CharField(max_length=200, verbose_name='Название опроса')),
                ('start_date', models.DateTimeField(default=datetime.datetime(2021, 9, 2, 9, 29, 9, 619782), verbose_name='Дата и время начало опроса')),
                ('end_date', models.DateTimeField(default=datetime.datetime(2021, 9, 12, 9, 29, 9, 619782), verbose_name='Дата и время окончание опроса')),
                ('description', models.TextField(verbose_name='Описание опроса')),
            ],
            options={
                'verbose_name': 'Опрос',
                'verbose_name_plural': 'Опросы',
                'ordering': ['-create_at'],
            },
        ),
        migrations.CreateModel(
            name='SurveyResponder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.ManyToManyField(through='cars.Answer', to='cars.Question', verbose_name='Ответы пользователя')),
                ('responder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.responder', verbose_name='Пользователь')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.survey', verbose_name='Опрос')),
            ],
            options={
                'verbose_name': 'Опрос который прощел пользователь',
                'verbose_name_plural': 'Опросы которые прощел пользователь',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='responder',
            name='survey',
            field=models.ManyToManyField(through='cars.SurveyResponder', to='cars.Survey', verbose_name='Опросы'),
        ),
        migrations.AddField(
            model_name='question',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.survey', verbose_name='Опрос'),
        ),
        migrations.CreateModel(
            name='AnswerQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Ответ к вопросу')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.question', verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответы',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.question', verbose_name='Вопрос'),
        ),
        migrations.AddField(
            model_name='answer',
            name='responder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.surveyresponder', verbose_name='Пользователь'),
        ),
    ]
