# Generated by Django 3.2.6 on 2021-09-02 07:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_auto_20210902_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 12, 13, 31, 26, 731035), verbose_name='Дата и время окончание опроса'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 2, 13, 31, 26, 731035), verbose_name='Дата и время начало опроса'),
        ),
    ]
