# Generated by Django 3.2.6 on 2021-09-03 05:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0010_auto_20210903_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 13, 11, 17, 2, 541720), verbose_name='Дата и время окончание опроса'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 3, 11, 17, 2, 541720), verbose_name='Дата и время начало опроса'),
        ),
    ]
